# vim:ft=kitty
font_size                   14.0
# modify_font					cell_height 120%

disable_ligatures           cursor
enable_audio_bell			no
cursor_shape                block
cursor_beam_thickness       10
cursor_blink_interval		0
scrollback_lines            1000
window_padding_width        30
background_opacity          1.0
tab_bar_style				fade
tab_powerline_style			round
scrollback_pager			nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
cursor_trail				1
cursor_trail_decay			0.1 0.3
pixel_scroll				no

include                     ~/.config/kitty/themes/nord.conf


# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' style=Light variable_name=JetBrainsMono
bold_font        family='JetBrains Mono' style=Regular variable_name=JetBrainsMono
italic_font      family='JetBrains Mono' style=Light variable_name=JetBrainsMono
bold_italic_font family='JetBrains Mono' style=Light variable_name=JetBrainsMono
# END_KITTY_FONTS
