# vim:ft=kitty

font_family                 JetBrainsMono NFM
bold_font                   JetBrainsMono NFM
italic_font                 JetBrainsMono NFM
bold_italic_font            JetBrainsMono NFM

# font_family					Terminess Nerd Font Mono
font_size                   12.0
modify_font					cell_height 110%

disable_ligatures           cursor
enable_audio_bell			no
cursor_shape                block
cursor_beam_thickness       10
cursor_blink_interval		0
scrollback_lines            1000
window_padding_width        30
background_opacity          1.0
tab_bar_style				powerline
tab_powerline_style			round

include                     ~/.config/kitty/gruvbox.conf
