[main]
# font=RobotoMono Nerd Font Mono:size=16
font=SF Mono:size=14,style=Bold

dpi-aware=yes
prompt="Start: "
icons-enabled=no

# Gruvbox
[colors]
background=#1D2021FF
text=#EBD2BBFF
match=#83A598FF
selection=#8EC07CFF
selection-text=#1D2021FF
selection-match=#1D2021FF
border=#1D2021FF

[border]
radius=40
