#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width            0
bspc config window_gap              16

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config presel_feedback_color   \#8ec07c
bspc config focused_border_color    \#fe8019
bspc config active_border_color     \#1d2021
bspc config normal_border_color     \#1d2021

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
# bspc rule -a eww state=floating manage=off

# feh --bg-fill ~/Pictures/gruvbox/gruvbox-wallpapers/wallpapers/pixelart/house-garden.jpg &
setxkbmap -option "ctrl:swapcaps" &
feh --bg-fill ~/Pictures/walls/gruvbox/gruvboxNoMansSky.jpg --xinerma-index 0 &
feh --bg-fill ~/Pictures/walls/gruvbox/gruvboxNoMansSky.jpg --xinerma-index 1 &
pidof picom && pkill picom
picom -f &
pidof eww && killall eww
# $HOME/Software/eww/target/release/eww daemon &
libinput-gestures &
$HOME/Software/eww/target/release/eww open bar &
pidof urxvtd || urxvtd &
xsetroot -cursor_name left_ptr
# pidof dunst && pkill dunst
# dunst &

