# local c = {
#   bg       = '#B8B8B8',  -- mid-light grey
#   fg       = '#505050',  -- soft mid grey
#   dim      = '#909090',  -- grey (comments)
#   bright   = '#383838',  -- cold spots - subtle thermal dips
#   subtle   = '#A8A8A8',  -- barely-there (line numbers)
#   visual   = '#ACACAC',  -- selection
#   cursor   = '#B0B0B0',  -- cursor line
#   border   = '#A8A8A8',  -- window borders
#   float_bg = '#BCBCBC',  -- floating windows
# }
# vim.g.terminal_color_0  = c.fg
# vim.g.terminal_color_1  = c.fg
# vim.g.terminal_color_2  = c.fg
# vim.g.terminal_color_3  = c.fg
# vim.g.terminal_color_4  = c.fg
# vim.g.terminal_color_5  = c.fg
# vim.g.terminal_color_6  = c.fg
# vim.g.terminal_color_7  = c.subtle
# vim.g.terminal_color_8  = c.dim
# vim.g.terminal_color_9  = c.fg
# vim.g.terminal_color_10 = c.fg
# vim.g.terminal_color_11 = c.fg
# vim.g.terminal_color_12 = c.fg
# vim.g.terminal_color_13 = c.fg
# vim.g.terminal_color_14 = c.fg
# vim.g.terminal_color_15 = c.bg
# MFD FLIR Theme
background #B8B8B8
foreground #505050
selection_background #ACACAC
selection_foreground #383838
url_color #383838
cursor #909090
active_border_color #505050
inactive_border_color #202020
active_tab_background #151515
active_tab_foreground #D0D0D0
inactive_tab_background #202020
inactive_tab_foreground #B0B0B0
tab_bar_background #202020

# normal
color0 #505050
color1 #505050
color2 #505050
color3 #505050
color4 #505050
color5 #505050
color6 #505050
color7 #A8A8A8

# bright
color8 #909090
color9 #505050
color10 #505050
color11 #505050
color12 #505050
color13 #505050
color14 #505050
color15 #B8B8B8
