# gruvbox-dark colorscheme for kitty
# snazzy theme used as base

foreground            #f2f4f8
background            #161616

selection_foreground  #262626
selection_background  #f2f4f8
url_color             #FF6F00

active_tab_background #ff7eb6
active_tab_foreground #262626
inactive_tab_background #393939
inactive_tab_foreground #f2f4f8

# black
color0   #161616
color8   #161616

# red
color1   #ee5396
color9   #ee5396

# green
color2   #42be65
color10  #42be65

# yellow
color3   #82cfff
color11  #82cfff

# blue
color4  #78a9ff
color12 #33b1ff

# magenta
color5   #ff7eb6
color13  #be95ff

# cyan
color6   #33b1ff
color14  #3ddbd9

# white
color7   #dde1e6
color15  #f2f4f8
