set -sg default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g base-index 1
set -g allow-passthrough on
set -g set-clipboard on
set -g renumber-windows on
set-window-option -g mode-keys vi

source-file ~/.config/tmux/themes/gruvbox.tmux
# source-file ~/.config/tmux/themes/osaka.tmux
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre

bind '\' display-popup -E  -w 80% -h 60%
