[main]

term=xterm-256color
# font=JetBrainsMono NFM:size=14
# font-bold=JetBrainsMono NFM:size=14
# font-italic=JetBrainsMono NFM:size=14
# font-bold-italic=JetBrainsMono NFM:size=14

pad=30x30

font=IosevkaTerm NFM:size=14
font-bold=IosevkaTerm NFM:size=14
font-italic=IosevkaTerm NFM:size=14
font-bold-italic=IosevkaTerm NFM:size=14

[colors]
foreground=D4BE98
background=1D2021
# background=000000
regular0=1D2021
regular1=FB4934
regular2=B8BB26
regular3=FABD2F
regular4=83A598
regular5=D3869B
regular6=8EC07C
regular7=D4BE98
bright0=1D2021
bright1=FB4934
bright2=B8BB26
bright3=FABD2F
bright4=83A598
bright5=D3869B
bright6=8EC07C
bright7=D4BE98
dim0=1D2021
dim1=FB4934
dim2=B8BB26
dim3=FABD2F
dim4=83A598
dim5=D3869B
dim6=8EC07C
dim7=D4BE98

# [colors]
# foreground=ffffff
# background=000000
# selection-foreground=ffffff
# selection-background=7030af
# urls=c6daff

# regular0=000000
# regular1=ff5f59
# regular2=44bc44
# regular3=d0bc00
# regular4=2fafff
# regular5=feacd0
# regular6=00d3d0
# regular7=a6a6a6

# bright0=595959
# bright1=ff6b55
# bright2=00c06f
# bright3=fec43f
# bright4=79a8ff
# bright5=f78fe7
# bright6=6ae4b9
# bright7=ffffff

# 16=fec43f
# 17=ff9580
